### ISSUE TITLE
ExceededTimeLimit exceptions should not be classified as errors

### ISSUE THREAD

**Issue by coot** [input-output-hk/ouroboros-network#3049]
The following one is classified as an `Error`
```
[neptune:cardano.node.DnsSubscription:Error:32402] [2021-04-07 06:45:13.50 UTC] Domain: "relays-new.cardano-mainnet.iohk.io" Application Exception: 3.129.48.231:3001 ExceededTimeLimit (ChainSync (Header (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (Tip HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ServerAgency TokNext TokMustReply)
```

But this one is classified as a `Notice`:
```
{"thread":"180","loc":null,"data":{"address":"52.26.127.70:38909","kind":"ErrorPolicyTrace","event":"ErrorPolicySuspendConsumer (Just (ApplicationExceptionTrace ExceededTimeLimit (TxSubmission TxId (GenTx (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) GenTx (HardForkBlock (': * ByronBlock (': * (ShelleyBlock (ShelleyEra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Allegra StandardCrypto)) (': * (ShelleyBlock (ShelleyMAEra 'Mary StandardCrypto)) ('[] *))))))) (ClientAgency TokTxs))) 20s"},"sev":"Notice","env":"1.26.1:62f38","msg":"","app":[],"host":"Server-D","pid":"2798","ns":["cardano.node.ErrorPolicy"],"at":"2021-04-07T16:52:12.34Z"}
```

**Comment by bolt12** [comment]
I looked into this:

In `configuration/chairman/byron-shelley/configuration.yaml` there is a config setting that sets `DnsSubscription` as `Debug`:

```yaml
# apply a filter on message severity on messages in a specific named context.
# this filter is applied additionally to the global 'minSeverity' and thus
# needs to be at least as high.
mapSeverity:
  cardano.node.ChainDB: Notice
  cardano.node.DnsSubscription: Debug
  cardano.node.TraceIpSubscription: Info
  cardano.node.TraceMux: Info
  cardano.node.Handshake: Debug
```

and in `cardano-node/src/Cardano/Tracing/OrphanInstances/Network.hs`, the `HasSeverityAnnotation` instance for `WithAddr addr ErrorPolicyTrace` has `ErrorPolicySuspenderConsumer` as `Notice`:

```haskell
instance HasSeverityAnnotation (WithAddr addr ErrorPolicyTrace) where
  getSeverityAnnotation (WithAddr _ ev) = case ev of
    ErrorPolicySuspendPeer {} -> Warning -- peer misbehaved
    ErrorPolicySuspendConsumer {} -> Notice -- peer temporarily not useful
    ErrorPolicyLocalNodeError {} -> Error
    ErrorPolicyResumePeer {} -> Debug
    ErrorPolicyKeepSuspended {} -> Debug
    ErrorPolicyResumeConsumer {} -> Debug
    ErrorPolicyResumeProducer {} -> Debug
    ErrorPolicyUnhandledApplicationException {} -> Error
    ErrorPolicyUnhandledConnectionException {} -> Error
    ErrorPolicyAcceptException {} -> Error
```

The problem is that `ExceededTimeLimit` is not incorrectly classified but rather the triggering errors are. Since `ExceededTimeLimit` is hidden behind the `SomeException` type in all cases, one way to try to tackle this issue might be pattern matching on every `SomeException` and see if it matches `ExceededTimeLimit :: ProtocolLimitFailure`. However this solution is not very good because there are a lot of data types that have nested `SomeExcepetion` types...
